/**
 * Augments the ambient CloudflareEnv interface with the quote form's runtime
 * secrets (CLAUDE.md §4.3, §8). Deliberately NOT added to cloudflare-env.d.ts —
 * that file is regenerated by `npm run cf-typegen` and hand-edits there would
 * be lost. Declaring the extra keys here, in a file wrangler never touches,
 * survives regeneration.
 *
 * These are set with `wrangler secret put <NAME>` against the Cloudflare
 * account directly, never written to wrangler.jsonc or committed anywhere.
 */
declare global {
  interface CloudflareEnv {
    /** Discord webhook URL the quote handler posts new leads to. */
    DISCORD_WEBHOOK_URL: string;
  }
}

export {};
